name: Daily Web Scrape

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:       # Allows manual triggering
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
        playwright install-deps
        
    - name: Run scraping script
      run: python app.py
      
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: scraping-results
        path: data.xlsx

    - name: Commit results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.xlsx
        git commit -m "Update scraped data" || echo "No changes to commit"
        git push
    env:
      ACTIONS_STEP_DEBUG: true
#es
